#if !canImport(ObjectiveC)
import XCTest

extension SmartQuotesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SmartQuotesTests = [
        ("testSmartQuotes", testSmartQuotes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SmartQuotesTests.__allTests__SmartQuotesTests),
    ]
}
#endif
