name: Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Swift tests
      uses: docker://swift/latest
      with:
        entrypoint: swift
        args: test